import express from 'express';
import type { Request, Response } from 'express';

const app = express();
const port: number = 3000;

app.use(express.json());

app.get('/', (req: Request, res: Response) => {
  res.send('Hello, World!');
});

app.post('/users', (req: Request, res: Response) => {
  const user = req.body;
  console.log(user);

  res.status(201).json({
    id: 1, // This would be generated by the database
    ...user,
  });
});

app.listen(port, () => {
  console.log(`API is running at http://localhost:${port}`);
});
